classDiagram

namespace PkgCompetences {
  class Competence
  class Technologie
  class NiveauCompetence
  class NiveauDifficulte
  class CategorieTechnologie
}

namespace PkgFormation {
  class Module
  class Formateur
}

class Competence {
  +id: bigint
  +code: string
  +nom: string
}

class Technologie {
  +id: bigint
  +nom: string
  +description: text
}

class NiveauCompetence {
  +id: bigint
  +nom: string
  +description: text
}

class NiveauDifficulte {
  +id: bigint
  +nom: string
  +description: text
}

class CategorieTechnologie {
  +id: bigint
  +nom: string
  +description: text
}




Competence "*" --> "1" Module
Competence "1" --> "*" NiveauCompetence
Competence "*" -- "*" Technologie

Technologie "*" --> "1" CategorieTechnologie

NiveauDifficulte "*" --> "1" Formateur

Technologie "*" --> "*" TransfertCompetence